name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: Features
    labels:
      - 'feature'
      - 'enhancement'
  - title: Bug Fixes
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: Maintenance
    label: 'chore'
  - title: Miscellaneous #Everything except ABAP
    label: 'misc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch

include-labels:
  - 'breaking-change'
  - 'enhancement'
  - 'bug'

template: |
  ## Changes
  $CHANGES